manifest_schema = 1
distribution = "streamlit-graph-canvas-contrib"
version = "0.1.0rc2"
renderer_api = ">=1,<2"

[[renderers]]
kind = "streamlit-graph-canvas/contrib/count-chip"
python = "streamlit_graph_canvas_contrib.count_chip:renderer"
javascript = "frontend/renderer-bootstrap.2336405d91efba504af52dd65115b287771bc946a0b4a9413e610dbf3cdc15b3.js"
javascript_component = "streamlit-graph-canvas-contrib.renderer_bootstrap"
javascript_entry = "renderer-bootstrap.2336405d91efba504af52dd65115b287771bc946a0b4a9413e610dbf3cdc15b3.js"
javascript_identity = "2b3ec04249bd7235aeedb01acf385c7a5fcde390ca4b366086fa90411616918b"
transports = ["prims", "javascript", "raster", "atlas"]

[assets]
"frontend/renderer-bootstrap.2336405d91efba504af52dd65115b287771bc946a0b4a9413e610dbf3cdc15b3.js" = "2336405d91efba504af52dd65115b287771bc946a0b4a9413e610dbf3cdc15b3"
