import {test,expect} from '@playwright/test';
import {waitForGalleryStable} from '../tests/harness';
test('fixed label policies preserve full labels, search, and geometry',async({page,context})=>{
 await context.grantPermissions(['clipboard-read','clipboard-write']);
 await page.goto('/');await waitForGalleryStable(page);
 const path=page.getByTestId('rf__node-path');
 const lines=path.locator('.sgc-node-label > span');
 await expect(lines).toHaveCount(2);await expect(lines.nth(0)).toContainText('…');await expect(lines.nth(1)).toHaveText('packages-lock.json');
 const single=page.getByTestId('rf__node-single');
 await expect(single.locator('.sgc-node-label > span')).toHaveCount(1);
 await expect(single.locator('.sgc-node-label')).toContainText('…');
 await expect(single.locator('.sgc-label-reveal')).toHaveCount(0);
 await expect(page.getByTestId('rf__node-compact').locator('.sgc-node-label')).toHaveText('short.csproj');
 const size=await page.getByTestId('rf__node-shrink').locator('.sgc-node-label').evaluate(n=>parseFloat(getComputedStyle(n).fontSize));
 expect(size).toBeLessThan(14);expect(size).toBeGreaterThanOrEqual(8);
 const before=await path.getAttribute('style'),runs=await page.getByText(/^Runs: /).textContent();
 await path.locator('.sgc-node').focus();
 await expect(page.getByRole('tooltip')).toContainText('src/integrations/prefect/infra/packages-lock.json');
 await path.locator('.sgc-label-reveal').click();
 await expect(page.getByRole('button',{name:'Copy full label',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Copy full label',exact:true}).click();
 await expect(page.getByRole('button',{name:'Copied',exact:true})).toBeVisible();
 expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe('src/integrations/prefect/infra/packages-lock.json');
 await path.locator('.sgc-label-reveal').press('Escape');
 await expect(page.getByRole('dialog',{name:'Full node label'})).toHaveCount(0);
 await path.locator('.sgc-label-reveal').click();
 await page.getByRole('button',{name:'Close',exact:true}).click();
 expect(await path.getAttribute('style')).toEqual(before);
 expect(await page.getByText(/^Runs: /).textContent()).toEqual(runs);
 await page.getByText('Find in this view',{exact:true}).click();
 await page.getByRole('textbox',{name:'Find node names'}).fill('full-searchable');
 await expect(page.locator('.sgc-search-match')).toHaveAttribute('data-id','compact');
 const overflow=await page.locator('.sgc-node-label > span').evaluateAll(ns=>ns.some(n=>n.scrollWidth>n.clientWidth+1));
 expect(overflow).toBe(false);
});

test('delayed reveal is limited to shortened names and cancels when leaving',async({page})=>{
 await page.goto('/');await waitForGalleryStable(page);
 const node=page.getByTestId('rf__node-delayed');
 const name=node.locator('.sgc-node-label');
 await expect(node.locator('.sgc-label-reveal')).toHaveCount(0);
 await node.locator('.sgc-node-type').hover();await page.waitForTimeout(1150);
 await expect(page.getByRole('tooltip')).toHaveCount(0);
 await page.getByTestId('rf__node-short').locator('.sgc-node-label').hover();await page.waitForTimeout(1150);
 await expect(page.getByRole('tooltip')).toHaveCount(0);
 const runs=await page.getByText(/^Runs: /).textContent();
 await name.hover();await page.waitForTimeout(250);
 await expect(page.getByRole('tooltip')).toHaveCount(0);
 await page.mouse.move(0,0);await page.waitForTimeout(1150);
 await expect(page.getByRole('tooltip')).toHaveCount(0);
 await name.hover();
 await expect(page.getByRole('tooltip')).toContainText('very/long/directory/another/long/file-name.csproj');
 await page.mouse.move(0,0);await expect(page.getByRole('tooltip')).toHaveCount(0);
 await page.getByTestId('rf__node-alias').locator('.sgc-node-label').hover();
 await expect(page.getByRole('tooltip')).toContainText('full/original/name.csproj');
 expect(await page.getByText(/^Runs: /).textContent()).toEqual(runs);
});

test('appearance updates refresh labels without another layout; geometry still relayouts',async({page})=>{
 await page.goto('/');await waitForGalleryStable(page);
 const host=page.locator('[data-sgc-status=ready]');
 const count=await host.getAttribute('data-sgc-layout-count');
 const before=await page.getByTestId('rf__node-path').getAttribute('style');
 const delay=page.getByRole('spinbutton',{name:'Reveal delay',exact:true});
 await delay.fill('900');await delay.press('Enter');await waitForGalleryStable(page);
 expect(await host.getAttribute('data-sgc-layout-count')).toBe(count);
 const font=page.getByRole('spinbutton',{name:'Label font size',exact:true});
 await font.fill('12');await font.press('Enter');await waitForGalleryStable(page);
 await expect(page.getByTestId('rf__node-path').locator('.sgc-node-label')).toHaveCSS('font-size','12px');
 expect(await host.getAttribute('data-sgc-layout-count')).toBe(count);
 expect(await page.getByTestId('rf__node-path').getAttribute('style')).toBe(before);
 const width=page.getByRole('spinbutton',{name:'Node width',exact:true});
 await width.fill('240');await width.press('Enter');await waitForGalleryStable(page);
 expect(Number(await host.getAttribute('data-sgc-layout-count'))).toBeGreaterThan(Number(count));
 const reveal=page.getByTestId('rf__node-path').locator('.sgc-label-reveal');
 await reveal.click();await expect(page.getByRole('dialog',{name:'Full node label'})).toBeVisible();
 await page.locator('.react-flow__controls-zoomin').click();
 await expect(page.getByRole('dialog',{name:'Full node label'})).toHaveCount(0);
});
