import { test, expect } from "@playwright/test";
import { waitForGalleryStable } from "../tests/harness";
test("typing previews locally, Apply reorders, Clear restores, callbacks are explicit",async({page})=>{
  await page.goto('/');await waitForGalleryStable(page);
  const positions=()=>page.locator('.react-flow__node').evaluateAll(nodes=>Object.fromEntries(nodes.map(n=>[n.getAttribute('data-id'),(n as HTMLElement).style.transform])));
  const runs=()=>page.getByText(/^Runs: /).textContent();
  const before=await positions(),initialRuns=await runs();
  const target=await page.locator('.react-flow__node').evaluateAll(nodes=>nodes.filter(n=>['alpha','beta','gamma'].includes(n.getAttribute('data-id')!)).sort((a,b)=>new DOMMatrix((b as HTMLElement).style.transform).m41-new DOMMatrix((a as HTMLElement).style.transform).m41).map(n=>n.getAttribute('data-id')!)[0]);
  await page.getByText('Find in this view',{exact:true}).click();
  const input=page.getByRole('textbox',{name:'Find node names'});
  await input.fill(target);
  await expect(page.locator('.sgc-search-match')).toHaveCount(1);
  await expect(page.locator('.sgc-search-match')).toHaveAttribute('data-id',target);
  expect(await positions()).toEqual(before);
  expect(await runs()).toEqual(initialRuns);
  expect(await page.locator('.react-flow__node[data-id="'+(['alpha','beta','gamma'].find(n=>n!==target))+'"]').evaluate(n=>(n as HTMLElement).style.opacity)).toBe('0.25');
  await expect(page.getByRole('button',{name:'Send filters to app'})).toHaveCount(0);
  const evaluations=await page.locator('[data-sgc-status=ready]').getAttribute('data-sgc-search-evaluations');
  await page.getByRole('button',{name:'Apply search',exact:true}).click();await waitForGalleryStable(page);
  expect(await page.locator('[data-sgc-status=ready]').getAttribute('data-sgc-search-evaluations')).toBe(evaluations);
  const applied=await positions();expect(applied[target]).not.toEqual(before[target]);
  const x=await page.locator('.react-flow__node').evaluateAll(nodes=>Object.fromEntries(nodes.map(n=>[n.getAttribute('data-id'),new DOMMatrix((n as HTMLElement).style.transform).m41])));
  for(const id of ['alpha','beta','gamma'].filter(n=>n!==target))expect(x[target]).toBeLessThan(x[id]);
  await input.fill('beta');expect(await positions()).toEqual(applied);
  await page.getByRole('button',{name:'Clear search'}).click();await waitForGalleryStable(page);
  expect(await positions()).toEqual(before);
  await page.getByText('Filter criteria',{exact:true}).click();
  await page.getByRole('button',{name:'Add filter',exact:true}).click();
  await page.getByRole('spinbutton',{name:'Filter 1 value'}).fill('2');
  await expect(page.locator('.sgc-search-match')).toHaveCount(1);
  await page.getByRole('checkbox',{name:'Include context nodes'}).check();
  await expect(page.locator('.sgc-search-match')).toHaveCount(2);
  await page.getByRole('button',{name:'Clear search'}).click();
  await page.getByRole('checkbox',{name:'Enable search callback'}).press('Space');await waitForGalleryStable(page);
  await input.fill('gamma');
  await expect(page.getByText(/This callback reruns Streamlit/)).toBeVisible();
  const beforeSend=await runs();
  await input.fill('beta');expect(await runs()).toEqual(beforeSend);
  await page.getByRole('button',{name:'Send filters to app'}).click();
  await expect(page.getByText('Sent: 1',{exact:true})).toBeVisible();
  await expect(page.getByText('Requested: beta',{exact:true})).toBeVisible();
});

test("cached search follows metadata updates and collection visibility", async ({page}) => {
  await page.goto('/');await waitForGalleryStable(page);
  await page.getByText('Find in this view',{exact:true}).click();
  await page.getByText('Filter criteria',{exact:true}).click();
  await page.getByRole('button',{name:'Add filter',exact:true}).click();
  await page.getByRole('spinbutton',{name:'Filter 1 value'}).fill('2');
  await expect(page.locator('.sgc-search-match')).toHaveAttribute('data-id','gamma');
  const count=page.getByRole('spinbutton',{name:'Alpha count',exact:true});
  await count.fill('5');await count.press('Enter');await waitForGalleryStable(page);
  await expect(page.locator('.sgc-search-match')).toHaveCount(2);
  await expect(page.getByTestId('rf__node-alpha')).toHaveClass(/sgc-search-match/);
  await page.getByRole('checkbox',{name:'Collect children',exact:true}).press('Space');
  await waitForGalleryStable(page);
  await expect(page.locator('.sgc-search-match')).toHaveCount(0);
  const marker=page.locator('.sgc-group-marker[data-sgc-group="child"]');
  await marker.press('Enter');await waitForGalleryStable(page);
  await expect(page.locator('.sgc-search-match')).toHaveCount(2);
  await marker.press('Enter');await waitForGalleryStable(page);
  await expect(page.locator('.sgc-search-match')).toHaveCount(0);
});
