"""Generated cross-language protocol authority. Do not edit directly."""

CONTRACT_SCHEMA_VERSION = 1
CODEC_VERSION = 2
PROTOCOL_VERSION = 1
RENDERER_API = 1
RENDERER_REGISTRY_SYMBOL = "streamlit-graph-canvas.renderers.v1"
RENDERER_REGISTRATION_EVENT = "sgc-renderer-registered-v1"
MAX_ACTION_BATCH = 256
MAX_SELECTION = 700
MAX_IDENTIFIER_CHARS = 512
MAX_BROWSER_STATE_BYTES = 262144
MAX_DATA_DEPTH = 20
MAX_DATA_STRING_CHARS = 65536
MAX_COLLECTION_ITEMS = 10000
MAX_DATA_VALUES = 100000
MAX_ATLAS_DIMENSION = 4096
MAX_ATLAS_DECODED_PIXELS = 262144
MAX_ATLAS_PAGE_BYTES = 2097152
MAX_PRIMITIVE_COUNT = 200
MAX_PRIMITIVE_TEXT_CHARS = 1024
