"""Generate the human-readable compatibility matrix from dependency policy."""

from __future__ import annotations

import argparse
import tomllib
from pathlib import Path
from typing import Any


def render(policy: dict[str, Any]) -> bytes:
    lines = [
        "# Generated dependency compatibility matrix",
        "",
        "The [documentation generator](../ci/generate_dependency_docs.py) builds this",
        "matrix from the [dependency policy](../ci/dependency-policy.toml).",
        "To update it, edit the policy and run",
        "`uv run python -m ci.generate_dependency_docs --write`.",
        "Do not edit this file manually.",
        "",
        "## Toolchains",
        "",
        "| Toolchain | Minimum and locked versions | Forward version |",
        "| --- | --- | --- |",
        (
            f"| Python | {policy['toolchains']['python_min']} "
            f"(locked: {', '.join(policy['toolchains']['python_locked'])}) | "
            f"{policy['toolchains']['python_forward']} |"
        ),
        (
            f"| Node.js | `{policy['toolchains']['node_supported']}` "
            f"(locked: {policy['toolchains']['node_locked']}) | "
            f"{policy['toolchains']['node_forward']} |"
        ),
        "",
        "## Python runtime",
        "",
        "| Dependency | Minimum supported | Latest supported | Install range | "
        "Forward requirement | "
        "Risk |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for name, entry in policy["python"].items():
        forward = f"`{entry['forward']}`" if entry.get("forward") else "Not configured"
        lines.append(
            f"| `{name}` | {entry['minimum']} | {entry['latest_supported']} | "
            f"`{entry['supported']}` | "
            f"{forward} | {entry['risk'].capitalize()} |"
        )
    lines.extend(
        [
            "",
            "## Browser runtime dependencies",
            "",
            (
                "| Group | Dependency | Minimum supported | Latest supported | "
                "Install range | "
                "Forward tag | Coupled with | Risk |"
            ),
            "| --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    for group, entries in {"runtime": policy["npm"]["runtime"]}.items():
        for name, entry in entries.items():
            forward = (
                f"`{entry['forward']}`" if entry.get("forward") else "Not configured"
            )
            coupling = (
                ", ".join(
                    f"`{name.strip()}`"
                    for name in entry.get("coupling", "").split(",")
                    if name
                )
                or "None"
            )
            lines.append(
                f"| {group.capitalize()} | `{name}` | {entry['minimum']} | "
                f"{entry['latest_supported']} | `{entry['supported']}` | {forward} | "
                f"{coupling} | {entry['risk'].capitalize()} |"
            )
    lines.extend(
        [
            "",
            "## Internal JavaScript tools",
            "",
            "Tool version declarations come from the frontend and browser-test",
            "`package.json` files; exact resolutions come from their "
            "`package-lock.json`",
            "files. These tools have no separate minimum or latest-supported promise.",
            "Compatibility lanes use locked tools; advisory probes can test "
            "newer tools.",
            "",
            "| Group | Tool | Risk |",
            "| --- | --- | --- |",
        ]
    )
    for group in ("build", "test"):
        for name, entry in policy["npm"][group].items():
            lines.append(
                f"| {group.capitalize()} | `{name}` | {entry['risk'].capitalize()} |"
            )
    lines.extend(
        [
            "",
            "## CI signals",
            "",
            "The following CI lanes block releases:",
            "",
            *(f"- `{lane}`" for lane in policy["ci"]["blocking_lanes"]),
            "",
            "The following CI lanes provide advisory results:",
            "",
            *(f"- `{lane}`" for lane in policy["ci"]["advisory_lanes"]),
            "",
        ]
    )
    return "\n".join(lines).encode()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).parents[1])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args()
    policy = tomllib.loads(
        (args.root / "ci/dependency-policy.toml").read_text(encoding="utf-8")
    )
    content = render(policy)
    output = args.root / "docs/dependency-compatibility.generated.md"
    if args.check:
        if not output.is_file() or output.read_bytes() != content:
            raise SystemExit(
                "generated dependency compatibility documentation is stale"
            )
    else:
        output.write_bytes(content)
    print("dependency compatibility documentation is synchronized")


if __name__ == "__main__":
    main()
